[tool.poetry]
name = "search-offsets"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "search_offsets"}]

[tool.poetry.dependencies]
python = "^3.10"
more-itertools = "^10.2.0"
typer = "^0.12.3"
peclasses = {version = "^0.4.0", source = "dfint"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.7"

[tool.poetry.scripts]
search = "search_offsets.search:app"

[[tool.poetry.source]]
name = "dfint"
url = "https://dfint.github.io/pypi-index/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",
    "T201",  # `print` found
    "S101",  # Use of assert detected
    "ANN101",  # Missing type annotation for self in method
]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101",  # Don't warn about using of asserts in tests
    "ANN201",  # Ignore "Missing return type annotation for public function", tests don't return anything
    "D",  # Don't warn about missing documentation in tests
]
